Haqbahoo/Areas/CRM/Controllers/CategoryController.cs
using ApplicationLayer.Haqbahoo.IService;
using ApplicationLayer.Haqbahoo.Service;
using DomainLayer.Haqbahoo.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Haqbahoo.Areas.CRM.Controllers
{
    [Area("CRM")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;

        }
        public async Task<IActionResult> Index()
        {
            var category = await _categoryService.GetAllCategory();
            return View(category);
        }
        public IActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddCategory(Category category)
        {
            if(!ModelState.IsValid)
            {
                return View(category);
            }
            await _categoryService.AddCategory(category);
            return Redirect("/CRM/Category/Index");
        }
        public async Task<IActionResult> Edit(Guid categoryId)
        {
            var category = await _categoryService.GetCategoryById(categoryId);
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            bool status = await _categoryService.EditCategory(category);
            return Redirect("/CRM/Category/Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid categoryId)
        {
            if(categoryId != Guid.Empty)
            {
                bool status = await _categoryService.DeleteCategory(categoryId);
                return Redirect("/CRM/Category/Index");
            }
            return Redirect("/CRM/Category/Index");
        }
    }
}

Haqbahoo/Areas/CRM/Controllers/DashboardController.cs
using ApplicationLayer.Haqbahoo.IService;
using DomainLayer.Haqbahoo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Haqbahoo.Areas.CRM.Controllers
{
    [Area("CRM")]
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly IDashBoardService _dashboardService;
        public DashboardController(IDashBoardService dashBoardService)
        {
            _dashboardService = dashBoardService;
            
        }
        public async Task<IActionResult> Index()
        {
            var dashboard = new DashboardViewModel()
            {
                Dasboard = await _dashboardService.GetDashboard(),
            };
          
            return View(dashboard);
        }
    }
}

Haqbahoo/Areas/CRM/Controllers/FeatureController.cs
using ApplicationLayer.Haqbahoo.IService;
using ApplicationLayer.Haqbahoo.Service;
using DomainLayer.Haqbahoo.Entities;
using Haqbahoo.Helper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Bcpg.Sig;
using Stripe.Entitlements;
using System.Threading.Tasks;

namespace Haqbahoo.Areas.CRM.Controllers
{
    [Area("CRM")]
    [Authorize(Roles = "Admin")]
    public class FeatureController : Controller
    {
        private readonly IFeatureService _featureService;
     
        public FeatureController(IFeatureService featureService)
        {
            _featureService = featureService;
       

        }
        public async Task<IActionResult> Index()
        {
            var feature = await _featureService.GetAllFeature();
            return View(feature);
        }
        public IActionResult AddFeature()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddFeature(DomainLayer.Haqbahoo.Entities.Feature feature)
        {
            if(feature.ImageFile is null)
            {
                ModelState.AddModelError("ImageFile","Please upload an Image");
            }
            if(!ModelState.IsValid)
            {
                return View(feature);
            }
          
            await _featureService.AddFeature(feature);
            return Redirect("/CRM/Feature/Index");
        }
        public async Task<IActionResult> Edit(Guid featureId)
        {
            var feature = await _featureService.GetFeatureById(featureId);
            return View(feature);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(DomainLayer.Haqbahoo.Entities.Feature feature)
        {
            if (!ModelState.IsValid)
            {
                return View(feature);
            }
            bool status = await _featureService.EditFeature(feature);
            return Redirect("/CRM/Feature/Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            if(id != Guid.Empty)
            {
                bool status = await _featureService.DeleteFeature(id);
                return Redirect("/CRM/Feature/Index");
            }
            return Redirect("/CRM/Feature/Index");
        }
    }
}

Haqbahoo/Areas/CRM/Views/Feature/AddFeature.cshtml
@using DomainLayer.Haqbahoo.Entities
@model Feature
<div class="page-content">
	<div class="page-bar">
		<div class="page-title-breadcrumb">
			<div class=" pull-left">
				<div class="page-title">Add Feature</div>
			</div>
			<ol class="breadcrumb page-breadcrumb pull-right">
				<li>
					<i class="fa fa-home"></i>&nbsp;<a class="parent-item"
											 asp-asp-area="CRM" asp-controller="Dashboard" asp-action="index">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
				</li>
			
				<li class="active">Add Feature</li>
			</ol>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="card-box">

				<form method="post" enctype="multipart/form-data">

					
					<partial name="_FeatureForm" model="Model" />
				</form>
			</div>

		</div>
	</div>
</div>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />


	}
}

Haqbahoo/Areas/CRM/Views/Feature/Edit.cshtml
@using DomainLayer.Haqbahoo.Entities
@model Feature
<div class="page-content">
	<div class="page-bar">
		<div class="page-title-breadcrumb">
			<div class=" pull-left">
				<div class="page-title">Edit Feature</div>
			</div>
			<ol class="breadcrumb page-breadcrumb pull-right">
				<li>
					<i class="fa fa-home"></i>&nbsp;<a class="parent-item"
											 asp-asp-area="CRM" asp-controller="Dashboard" asp-action="index">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
				</li>
				
				<li class="active">Edit Feature</li>
			</ol>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="card-box">

				<form method="post" enctype="multipart/form-data">

					<input type="hidden" asp-for="Id" />
					<partial name="_FeatureForm" model="Model" />
				</form>
			</div>


		</div>
	</div>
</div>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />


	}
}

Haqbahoo/Areas/CRM/Views/Feature/Index.cshtml
@using DomainLayer.Haqbahoo.Entities
@model IEnumerable<Feature>
<!-- start page content -->
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="page-bar">
			<div class="page-title-breadcrumb">
				<div class=" pull-left">
					<div class="page-title">Feature List</div>
				</div>
				<ol class="breadcrumb page-breadcrumb pull-right">
					<li>
						<i class="fa fa-home"></i>&nbsp;<a class="parent-item"
											   asp-asp-area="CRM" asp-controller="Dashboard" asp-action="index">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					@* 	<li>
						<a class="parent-item" href="">Professors</a>&nbsp;<i class="fa fa-angle-right"></i>
					</li> *@
					<li class="active">Feature List</li>
				</ol>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="tabbable-line">
					<!-- <ul class="nav nav-tabs">
						<li class="active">
							<a href="#tab1" data-bs-toggle="tab"> List View </a>
						</li>
						<li>
							<a href="#tab2" data-bs-toggle="tab"> Grid View </a>
						</li>
					</ul> -->
					<ul class="nav customtab nav-tabs" role="tablist">
						<li class="nav-item">
							<a href="#tab1" class="nav-link active"
							   data-bs-toggle="tab">
								List
								View
							</a>
						</li>

					</ul>
					<div class="tab-content">
						<div class="tab-pane active fontawesome-demo" id="tab1">
							<div class="row">
								<div class="col-md-12">
									<div class="card card-box">
										<div class="card-head">
											<header>All Feature</header>
											<div class="tools">
												<a class="fa fa-repeat btn-color box-refresh"
												   href="javascript:;"></a>
												<a class="t-collapse btn-color fa fa-chevron-down"
												   href="javascript:;"></a>
												<a class="t-close btn-color fa fa-times"
												   href="javascript:;"></a>
											</div>
										</div>
										<div class="card-body ">
											<div class="row">
												<div class="col-md-6 col-sm-6 col-6">
													<div class="btn-group">
														<a asp-controller="feature" asp-area="CRM" asp-action="AddFeature" id="addRow"
														   class="btn btn-primary">
															Add New <i class="fa fa-plus"></i>
														</a>
													</div>
												</div>
											</div>
											<table class="table table-striped table-bordered table-hover table-checkable order-column valign-middle"
												   id="example4">
												<thead>
													<tr>
														<th></th>
														<th> Name </th>

														<th> Action </th>
													</tr>
												</thead>
												<tbody>
													@foreach (var feature in Model)
													{
														<tr class="odd gradeX">
															<td class="patient-img">
																<img src="/@feature.ImageUrl" alt="">
															</td>
															<td>@feature.Name</td>

															<td>
																<a asp-area="CRM" asp-controller="Feature" asp-action="Edit" asp-route-featureId="@feature.Id"
																   class="tblEditBtn">
																	<i class="fa fa-pencil"></i>
																</a>
																@* <a class="tblDelBtn">
																	<i class="fa fa-trash-o"></i>
																</a> *@
																@* 		<form id="deleteForm-@category.Id" asp-area="CRM" asp-action="DeleteCategory" asp-controller="Category" class="mt-1" asp-route-categoryId="@category.Id" method="post" style=" display: inline-block; ">
																	<button type="button" onclick="confirmDelete('@category.Id')" class="tblDelBtn"><i class="fa fa-trash-o"></i></button>
																</form> *@
																<button type="button" onclick="confirmDelete('@feature.Id')" class="tblDelBtn">
																	<i class="fa fa-trash-o"></i>
																</button>
															</td>
														</tr>

													}

												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end page content -->
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />

		<script src="~/js/feature.js"></script>
	
	}
}