Haqbahoo/Areas/CRM/Controllers/CategoryController.cs
using ApplicationLayer.Haqbahoo.IService;
using ApplicationLayer.Haqbahoo.Service;
using DomainLayer.Haqbahoo.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Haqbahoo.Areas.CRM.Controllers
{
    [Area("CRM")]
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;

        }
        public async Task<IActionResult> Index()
        {
            var category = await _categoryService.GetAllCategory();
            return View(category);
        }
        public IActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddCategory(Category category)
        {
            if(!ModelState.IsValid)
            {
                return View(category);
            }
            await _categoryService.AddCategory(category);
            return Redirect("/CRM/Category/Index");
        }
        public async Task<IActionResult> Edit(Guid categoryId)
        {
            var category = await _categoryService.GetCategoryById(categoryId);
            return View(category);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View(category);
            }
            bool status = await _categoryService.EditCategory(category);
            return Redirect("/CRM/Category/Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid categoryId)
        {
            if(categoryId != Guid.Empty)
            {
                bool status = await _categoryService.DeleteCategory(categoryId);
                return Redirect("/CRM/Category/Index");
            }
            return Redirect("/CRM/Category/Index");
        }
    }
}

Haqbahoo/Areas/CRM/Controllers/DashboardController.cs
using ApplicationLayer.Haqbahoo.IService;
using DomainLayer.Haqbahoo.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Haqbahoo.Areas.CRM.Controllers
{
    [Area("CRM")]
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly IDashBoardService _dashboardService;
        public DashboardController(IDashBoardService dashBoardService)
        {
            _dashboardService = dashBoardService;
            
        }
        public async Task<IActionResult> Index()
        {
            var dashboard = new DashboardViewModel()
            {
                Dasboard = await _dashboardService.GetDashboard(),
            };
          
            return View(dashboard);
        }
    }
}

Haqbahoo/Areas/CRM/Controllers/WorkShopController.cs
using ApplicationLayer.Haqbahoo.IService;
using DomainLayer.Haqbahoo.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Haqbahoo.Areas.CRM.Controllers
{
    [Area("CRM")]
    [Authorize(Roles = "Admin")]
    public class WorkShopController : Controller
    {
        private readonly IWorkShopService _workShopService;
        public WorkShopController(IWorkShopService workShopService)
        {
            _workShopService = workShopService;

        }
        public async Task<IActionResult> Index()
        {
            var workshop = await _workShopService.GetAllWorkShop();
            return View(workshop);
        }
        public IActionResult AddWorkShop()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddWorkShop(WorkShop workshop)
        {
            if (!ModelState.IsValid)
            {
                return View(workshop);
            }
            if(workshop.CoverImageFile == null)
            {
               ModelState.AddModelError("CoverImageFile", "Please upload Image!");
                return View(workshop);

            }
            await _workShopService.AddWorkShop(workshop);
            return Redirect("/crm/workshop/Index");
        }
        public async Task<IActionResult> Edit(Guid workshopId)
        {
            var workshop = await _workShopService.GetWorkShopById(workshopId);
            return View(workshop);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(WorkShop workshop)
        {
            if (!ModelState.IsValid)
            {
                return View(workshop);
            }
            bool status = await _workShopService.EditWorkShop(workshop);
            return Redirect("/CRM/workshop/Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id != Guid.Empty)
            {
                bool status = await _workShopService.DeleteWorkShop(id);
                return Redirect("/crm/workshop/Index");
            }
            return Redirect("/crm/workshop/Index");
        }
    }
}

Haqbahoo/Controllers/WorkShopController.cs
using ApplicationLayer.Haqbahoo.IService;
using DomainLayer.Haqbahoo.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Haqbahoo.Controllers
{

    public class WorkShopController : Controller
    {
        private readonly IWorkShopService _workShopService;
        public WorkShopController(IWorkShopService workShopService)
        {
            _workShopService = workShopService;

        }

        public async Task<IActionResult> List()
        {
            HomeViewModel homeViewModel = new HomeViewModel();
            {
                homeViewModel.WorkShops = await _workShopService.GetAllWorkShop();
            }
            return View(homeViewModel);
        }
        public async Task<IActionResult> Detail(Guid id)
        {
            var workshop = await _workShopService.GetWorkShopById(id);
            return View(workshop);
        }

    }
}

Haqbahoo/Areas/CRM/Views/WorkShop/AddWorkShop.cshtml
@using DomainLayer.Haqbahoo.Entities
@model WorkShop
<div class="page-content">
	<div class="page-bar">
		<div class="page-title-breadcrumb">
			<div class=" pull-left">
				<div class="page-title">Add WorkShop</div>
			</div>
			<ol class="breadcrumb page-breadcrumb pull-right">
				<li>
					<i class="fa fa-home"></i>&nbsp;<a class="parent-item"
											 asp-asp-area="CRM" asp-controller="Dashboard" asp-action="index">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
				</li>
				
				<li class="active">Add WorkShop</li>
			</ol>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="card-box">

				<form method="post" enctype="multipart/form-data">

					
					<partial name="_WorkShopForm" model="Model" />
				</form>
			</div>

		</div>
	</div>
</div>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />


	}
}

Haqbahoo/Areas/CRM/Views/WorkShop/Edit.cshtml
@using DomainLayer.Haqbahoo.Entities
@model WorkShop
<div class="page-content">
	<div class="page-bar">
		<div class="page-title-breadcrumb">
			<div class=" pull-left">
				<div class="page-title">Edit WorkShop</div>
			</div>
			<ol class="breadcrumb page-breadcrumb pull-right">
				<li>
					<i class="fa fa-home"></i>&nbsp;<a class="parent-item"
											 asp-asp-area="CRM" asp-controller="Dashboard" asp-action="index">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
				</li>
				
				<li class="active">Edit WorkShop</li>
			</ol>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<div class="card-box">

				<form method="post" enctype="multipart/form-data">

					<input type="hidden" asp-for="Id" />
					<partial name="_WorkShopForm" model="Model" />
				</form>
			</div>


		</div>
	</div>
</div>
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />


	}
}

Haqbahoo/Areas/CRM/Views/WorkShop/Index.cshtml
@using DomainLayer.Haqbahoo.Entities
@model IEnumerable<WorkShop>
<!-- start page content -->
<div class="page-content-wrapper">
	<div class="page-content">
		<div class="page-bar">
			<div class="page-title-breadcrumb">
				<div class=" pull-left">
					<div class="page-title">WorkShop List</div>
				</div>
				<ol class="breadcrumb page-breadcrumb pull-right">
					<li>
						<i class="fa fa-home"></i>&nbsp;<a class="parent-item"
											   asp-asp-area="CRM" asp-controller="Dashboard" asp-action="index">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
					</li>
					@* 	<li>
						<a class="parent-item" href="">Professors</a>&nbsp;<i class="fa fa-angle-right"></i>
					</li> *@
					<li class="active">WorkShop List</li>
				</ol>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="tabbable-line">
					<!-- <ul class="nav nav-tabs">
						<li class="active">
							<a href="#tab1" data-bs-toggle="tab"> List View </a>
						</li>
						<li>
							<a href="#tab2" data-bs-toggle="tab"> Grid View </a>
						</li>
					</ul> -->
					<ul class="nav customtab nav-tabs" role="tablist">
						<li class="nav-item">
							<a href="#tab1" class="nav-link active"
							   data-bs-toggle="tab">
								List
								View
							</a>
						</li>

					</ul>
					<div class="tab-content">
						<div class="tab-pane active fontawesome-demo" id="tab1">
							<div class="row">
								<div class="col-md-12">
									<div class="card card-box">
										<div class="card-head">
											<header>All WorkShop</header>
											<div class="tools">
												<a class="fa fa-repeat btn-color box-refresh"
												   href="javascript:;"></a>
												<a class="t-collapse btn-color fa fa-chevron-down"
												   href="javascript:;"></a>
												<a class="t-close btn-color fa fa-times"
												   href="javascript:;"></a>
											</div>
										</div>
										<div class="card-body ">
											<div class="row">
												<div class="col-md-6 col-sm-6 col-6">
													<div class="btn-group">
														<a asp-controller="WorkShop" asp-area="CRM" asp-action="AddWorkShop" id="addRow"
														   class="btn btn-primary">
															Add New <i class="fa fa-plus"></i>
														</a>
													</div>
												</div>
											</div>
											<table class="table table-striped table-bordered table-hover table-checkable order-column valign-middle"
												   id="example4">
												<thead>
													<tr>
														@* <th></th> *@
														<th> Name </th>

														<th> Action </th>
													</tr>
												</thead>
												<tbody>
													@foreach (var workShop in Model)
													{
														<tr class="odd gradeX">
															@* <td class="patient-img">
																<img src="/assets/img/user/user1.jpg" alt="">
															</td> *@
															<td>@workShop.Title</td>

															<td>
																<a asp-area="CRM" asp-controller="workShop" asp-action="Edit" asp-route-workShopId="@workShop.Id"
																   class="tblEditBtn">
																	<i class="fa fa-pencil"></i>
																</a>
																@* <a class="tblDelBtn">
																	<i class="fa fa-trash-o"></i>
																</a> *@
																@* 		<form id="deleteForm-@category.Id" asp-area="CRM" asp-action="DeleteCategory" asp-controller="Category" class="mt-1" asp-route-categoryId="@category.Id" method="post" style=" display: inline-block; ">
																	<button type="button" onclick="confirmDelete('@category.Id')" class="tblDelBtn"><i class="fa fa-trash-o"></i></button>
																</form> *@
																<button type="button" onclick="confirmDelete('@workShop.Id')" class="tblDelBtn">
																	<i class="fa fa-trash-o"></i>
																</button>
															</td>
														</tr>

													}

												</tbody>
											</table>
										</div>
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end page content -->
@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
		<script src="~/js/workshop.js"></script>
	}
}